export const BADGE_DEFINITIONS = [
  {
    id: 'first_artwork',
    name: 'badges.list.first_artwork.name',
    description: 'badges.list.first_artwork.desc',
    icon: '🎨',
    requirement_type: 'artwork_count',
    requirement_value: 1,
    color: '#7C3AED',
  },
  {
    id: 'five_artworks',
    name: 'badges.list.five_artworks.name',
    description: 'badges.list.five_artworks.desc',
    icon: '🖼️',
    requirement_type: 'artwork_count',
    requirement_value: 5,
    color: '#3B82F6',
  },
  {
    id: 'ten_artworks',
    name: 'badges.list.ten_artworks.name',
    description: 'badges.list.ten_artworks.desc',
    icon: '⭐',
    requirement_type: 'artwork_count',
    requirement_value: 10,
    color: '#F59E0B',
  },
  {
    id: 'first_competition',
    name: 'badges.list.first_competition.name',
    description: 'badges.list.first_competition.desc',
    icon: '🏅',
    requirement_type: 'competition_count',
    requirement_value: 1,
    color: '#10B981',
  },
  {
    id: 'first_win',
    name: 'badges.list.first_win.name',
    description: 'badges.list.first_win.desc',
    icon: '🏆',
    requirement_type: 'first_win',
    requirement_value: 1,
    color: '#F97316',
  },
  {
    id: 'five_competitions',
    name: 'badges.list.five_competitions.name',
    description: 'badges.list.five_competitions.desc',
    icon: '🎯',
    requirement_type: 'competition_count',
    requirement_value: 5,
    color: '#EC4899',
  },
  {
    id: 'colorful_creator',
    name: 'badges.list.colorful_creator.name',
    description: 'badges.list.colorful_creator.desc',
    icon: '🌈',
    requirement_type: 'category_count',
    requirement_value: 3,
    color: '#14B8A6',
  },
  {
    id: 'streak_3',
    name: 'badges.list.streak_3.name',
    description: 'badges.list.streak_3.desc',
    icon: '🔥',
    requirement_type: 'weekly_streak',
    requirement_value: 3,
    color: '#EF4444',
  },
  {
    id: 'twenty_artworks',
    name: 'badges.list.twenty_artworks.name',
    description: 'badges.list.twenty_artworks.desc',
    icon: '💎',
    requirement_type: 'artwork_count',
    requirement_value: 20,
    color: '#06B6D4',
  },
  {
    id: 'fifty_artworks',
    name: 'badges.list.fifty_artworks.name',
    description: 'badges.list.fifty_artworks.desc',
    icon: '👑',
    requirement_type: 'artwork_count',
    requirement_value: 50,
    color: '#8B5CF6',
  },
  {
    id: 'hundred_artworks',
    name: 'badges.list.hundred_artworks.name',
    description: 'badges.list.hundred_artworks.desc',
    icon: '🌌',
    requirement_type: 'artwork_count',
    requirement_value: 100,
    color: '#D946EF',
  },
  {
    id: 'ten_competitions',
    name: 'badges.list.ten_competitions.name',
    description: 'badges.list.ten_competitions.desc',
    icon: '⚔️',
    requirement_type: 'competition_count',
    requirement_value: 10,
    color: '#DC2626',
  },
  {
    id: 'master_creator',
    name: 'badges.list.master_creator.name',
    description: 'badges.list.master_creator.desc',
    icon: '🎆',
    requirement_type: 'category_count',
    requirement_value: 5,
    color: '#D946EF',
  },
  {
    id: 'persistent_artist',
    name: 'badges.list.persistent_artist.name',
    description: 'badges.list.persistent_artist.desc',
    icon: '🚀',
    requirement_type: 'weekly_streak',
    requirement_value: 10,
    color: '#EAB308',
  },
  {
    id: 'two_artworks',
    name: 'badges.list.two_artworks.name',
    description: 'badges.list.two_artworks.desc',
    icon: '🖌️',
    requirement_type: 'artwork_count',
    requirement_value: 2,
    color: '#8B5CF6',
  },
  {
    id: 'thirty_artworks',
    name: 'badges.list.thirty_artworks.name',
    description: 'badges.list.thirty_artworks.desc',
    icon: '🌟',
    requirement_type: 'artwork_count',
    requirement_value: 30,
    color: '#3B82F6',
  },
  {
    id: 'seventy_five_artworks',
    name: 'badges.list.seventy_five_artworks.name',
    description: 'badges.list.seventy_five_artworks.desc',
    icon: '🔮',
    requirement_type: 'artwork_count',
    requirement_value: 75,
    color: '#EC4899',
  },
  {
    id: 'two_competitions',
    name: 'badges.list.two_competitions.name',
    description: 'badges.list.two_competitions.desc',
    icon: '🥈',
    requirement_type: 'competition_count',
    requirement_value: 2,
    color: '#6366F1',
  },
  {
    id: 'twenty_competitions',
    name: 'badges.list.twenty_competitions.name',
    description: 'badges.list.twenty_competitions.desc',
    icon: '🛡️',
    requirement_type: 'competition_count',
    requirement_value: 20,
    color: '#EF4444',
  },
  {
    id: 'fifty_competitions',
    name: 'badges.list.fifty_competitions.name',
    description: 'badges.list.fifty_competitions.desc',
    icon: '🌠',
    requirement_type: 'competition_count',
    requirement_value: 50,
    color: '#F59E0B',
  },
  {
    id: 'two_categories',
    name: 'badges.list.two_categories.name',
    description: 'badges.list.two_categories.desc',
    icon: '🎭',
    requirement_type: 'category_count',
    requirement_value: 2,
    color: '#10B981',
  },
  {
    id: 'four_categories',
    name: 'badges.list.four_categories.name',
    description: 'badges.list.four_categories.desc',
    icon: '🧩',
    requirement_type: 'category_count',
    requirement_value: 4,
    color: '#14B8A6',
  },
  {
    id: 'six_categories',
    name: 'badges.list.six_categories.name',
    description: 'badges.list.six_categories.desc',
    icon: '🏅',
    requirement_type: 'category_count',
    requirement_value: 6,
    color: '#8B5CF6',
  },
  {
    id: 'streak_5',
    name: 'badges.list.streak_5.name',
    description: 'badges.list.streak_5.desc',
    icon: '🌋',
    requirement_type: 'weekly_streak',
    requirement_value: 5,
    color: '#DC2626',
  },
  {
    id: 'streak_20',
    name: 'badges.list.streak_20.name',
    description: 'badges.list.streak_20.desc',
    icon: '☄️',
    requirement_type: 'weekly_streak',
    requirement_value: 20,
    color: '#9333EA',
  },
];

export function checkBadgeEligibility(badgeDef, stats) {
  switch (badgeDef.requirement_type) {
    case 'artwork_count':
      return stats.artworkCount >= badgeDef.requirement_value;
    case 'competition_count':
      return stats.competitionCount >= badgeDef.requirement_value;
    case 'first_win':
      return stats.hasWin;
    case 'category_count':
      return stats.categoryCount >= badgeDef.requirement_value;
    case 'weekly_streak':
      return stats.weeklyArtworkCount >= badgeDef.requirement_value;
    default:
      return false;
  }
}
